anchor: &background_color "#A00000"

bar:
  bar_name: "bar 1"
  bar_x_pos: 0
  bar_y_pos: 0
  bar_width: 1920
  bar_height: 30
  bar_background_color: *background_color

  texts:
    - text_name: "text 1"
      text_value: "Hello, it's matoruru. "
      text_font: Iosevka Nerd Font Mono:pixelsize=30
      text_color: black
      text_background_color: *background_color
      text_x_pos: 30
      text_y_pos: 25

    - text_name: "text 2"
      text_value: "This is second text"
      text_font: MonoLisa:pixelsize=20
      text_color: pink3
      text_background_color: *background_color
      text_x_pos: 560
      text_y_pos: 23

    - text_name: "text 3"
      text_value: "This is third text"
      text_font: Fantasque Sans Mono:pixelsize=15
      text_color: black
      text_background_color: *background_color
      text_x_pos: 1200
      text_y_pos: 23
